### ISSUE TITLE
Use jetty instead of tomcat

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#10]
And talk to Alex F to make sure we don't use the version with a bug

**Comment by j-barber** [comment]
What's the benefit of Jetty vs. Tomcat?

**Comment by GalateaRaj** [comment]
Mainly performance.  We've run several tests on client projects and jetty seems to perform much better than tomcat.

**Comment by gala-dan** [comment]
Link to Spring docs on how - https://docs.spring.io/spring-boot/docs/1.5.10.RELEASE/reference/html/howto-embedded-servlet-containers.html#howto-use-jetty-instead-of-tomcat
