### ISSUE TITLE
Add to do to check jvm args

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#12]

**Comment by j-barber** [comment]
Is this a duplicate of #5 (JVM args)?

**Comment by GalateaRaj** [comment]
This one is to add a //TODO:  in Fuse code somewhere (or on a checklist) to make sure the application developer who is using FUSE double checks that the JVM args are relevant to their project.

#5 is actually to come up with FUSE recommended JVM args.

**Comment by GalateaEric** [comment]
closing as duplicate of #5 for the time being.
