### ISSUE TITLE
Remove fuse-starter-java.iml from project

### ISSUE THREAD

**Issue by paulo-reichert** [GalateaRaj/fuse-starter-java#127]
This file should be removed from GitHub and added to .gitignore. IntelliJ Idea will modify this file for various reasons during a normal session forcing constant recommits for no good reason. Each user can keep their own local version of this file and if for whatever reason it goes missing, just reopening the project from the pom.xml will create a fresh new one.

**Comment by gala-lightfoot** [comment]
PR'd [here](https://github.com/GalateaRaj/fuse-starter-java/pull/129).
