### ISSUE TITLE
Ignore generated code from SonarQube analysis

### ISSUE THREAD

**Issue by paulo-reichert** [GalateaRaj/fuse-starter-java#133]
Follow instructions here: https://docs.sonarqube.org/display/SONAR/Narrowing+the+Focus#NarrowingtheFocus-IgnoreIssues

**Comment by paulo-reichert** [comment]
Also, set up exclusion policies to ensure code that does not need testing is not flagged in SQ.

**Comment by GalateaRaj** [comment]
Lombok generated code is the primary use case for this.  Let's make sure we make it really clear how people can exclude that from the code coverage metric that is used in the quality gate.

**Comment by paulo-reichert** [comment]
Need to check whether this is still necessary. We have updated the jacoco maven plugin to version 0.8 (#108) and that should exclude from the coverage reports any code that is annotated with `javax.annotation.Generated` and `lombok.Generated`. SonarQube uses the jacoco reports to calculate code coverage and should therefore not need any extra configuration to get that done.

**Comment by hstandring** [comment]
Just an observation, but I was doing some investigation on this and it doesn't seem like sonar supports the ability to exclude code from metrics based on the annotation yet.  It does allow you to exclude it from issues, but there's an outstanding jira to exclude from metrics https://jira.sonarsource.com/browse/SONARJAVA-2223

**Comment by hstandring** [comment]
@paulo-reichert in regards to your point above, note that the exclusion of autogenerated code occurs during report generation.  The jacoco .exec file will contain metrics for everything so the systems that generate the reports off of this need to know to exclude this code.  This should work if our sonar has been upgraded to use the 5.1 version of the SonarJava plugin.

Reference: https://stackoverflow.com/questions/48501606/filtering-coverage-with-lombok-gradle-jacoco-and-sonar

**Comment by paulo-reichert** [comment]
This seems to work fine with jacoco 0.8 and the proto files are excluded in pom.xml.
