### ISSUE TITLE
Add Code Owners

### ISSUE THREAD

**Issue by j-barber** [GalateaRaj/fuse-starter-java#134]
Specify code owners (see: https://help.github.com/articles/about-codeowners/) and require at least 2 to approve PRs before merges are allowed.

To start, owners will be:
- Raj
- James
- Paulo
- Eric
- Firsh
- Heather
- Tighe
- Ari
- Danny

**Comment by GalateaRaj** [comment]
If we decide to go with code owners, we'll have to update the GitHub Settings for the branch to require reviews from code owners.  Unfortunately, I don't know if we can require approval from AT LEAST 1 code owner or if ALL code owners are required to approve a PR.  We should definitely look into this as well.

Another option is to keep permissions as-is (i.e. at least 1 collaborator must approve the PR) but reduce the list of collaborators to the group above.  Everyone else will have to fork the repo before making changes.  Here is a good article on how to fork:  https://gist.github.com/Chaser324/ce0505fbed06b947d962

What I don't know is how issue assignment will work if people use forks.  Can you assign an issue to someone who is not a collaborator?  Hmm.. maybe not:  https://github.com/isaacs/github/issues/100

**Comment by j-barber** [comment]
"I don't know if we can require approval from AT LEAST 1 code owner or if ALL code owners are required to approve a PR. We should definitely look into this as well."

[This](https://help.github.com/articles/enabling-required-reviews-for-pull-requests/) shows "Require **an** approved review", so my guess is it requires at least 1. But we should verify..

![image](https://user-images.githubusercontent.com/23705265/36507034-7020d324-1726-11e8-8c23-b08d4204992a.png)

**Comment by GalateaRaj** [comment]
If we can require approval from AT LEAST 1 code owner, then I'm good to go with code owners.  You have my vote.

**Comment by j-barber** [comment]
Raj + Me = approved. Moving forward.

1. Define a CODEOWNERS file w/ the referenced list of users
2. Get Raj to update the approval required for a PR to "require review from Code Owners"
3. Confirm it works.
4. Close issue.

**Comment by j-barber** [comment]
Added all code owners but Firsh, Alex, and Ari, because I couldn't find their git-hub handles.

**Comment by j-barber** [comment]
Evidence of non code-owner unable to review:
![notcodeowner](https://user-images.githubusercontent.com/23705265/36601482-342c65dc-1883-11e8-8f72-12133458b31d.PNG)

Evidence of code-owner able to review:
![codeowner](https://user-images.githubusercontent.com/23705265/36601490-3b353296-1883-11e8-9de6-6885ff895c0f.png)

**Comment by j-barber** [comment]
Evidence of the update to include everyone named above as a Code Owner (paulo excluded b/c he raised the PR):
![image](https://user-images.githubusercontent.com/23705265/36602066-005b15bc-1885-11e8-9424-1c8385cd055c.png)
