### ISSUE TITLE
Allow simultaneous PR builds

### ISSUE THREAD

**Issue by j-barber** [GalateaRaj/fuse-starter-java#137]
Simultaneous PR builds will fail, since the push to CF and subsequent tests aren't sandboxed to the PR. Sandbox appropriately, and confirm that multiple PR builds can run at the same time.

**Comment by paulo-reichert** [comment]
Seems like we can name an application in CF by specifying a unique [appName](https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html):
> Cloud Foundry uses the app name to compose the route to the app, and deployment fails unless the app has a globally unique route. 

We can use tokens in Jenkins to specify a unique ID such as `${BUILD_NUMBER}` make the appName unique (https://wiki.jenkins.io/display/JENKINS/Cloud+Foundry+Plugin).

The caveat is that to do such a thing the application manifest needs to be specified inline. After reading the code in [GH](https://github.com/jenkinsci/cloudfoundry-plugin/tree/master/src/main/java/com/hpe/cloudfoundryjenkins) the plug-in does not allow another way to specify the appName:
```
public CloudFoundryPushTask(String target, String organization, String cloudSpace, String credentialsId, boolean selfSigned, int pluginTimeout, List<CloudFoundryPushPublisher.Service> servicesToCreate, CloudFoundryPushPublisher.ManifestChoice manifestChoice) {
    this.target = target;
    this.organization = organization;
    this.cloudSpace = cloudSpace;
    this.credentialsId = credentialsId;
    this.selfSigned = selfSigned;
    this.pluginTimeout = pluginTimeout;
    this.servicesToCreate = servicesToCreate;
    this.manifestChoice = manifestChoice;
}
```

**Comment by paulo-reichert** [comment]
Another side-effect of the lack of sandboxing is that concurrent builds that deploy to CF are killing the fuse-rest-dev app and conflicting with another build at the integration tests stage, which will die with this error:

```
feign.FeignException: status 404 reading FuseServer#sendTradeAgreement(TradeAgreement[]); content:
404 Not Found: Requested route ('fuse-rest-dev.cfapps.io') does not exist.

	at feign.FeignException.errorStatus(FeignException.java:62)
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:134)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at org.galatea.starter.entrypoint.$Proxy45.sendTradeAgreement(Unknown Source)
	at org.galatea.starter.entrypoint.SettlementRestControllerIntegrationTest.testMissionCreation(SettlementRestControllerIntegrationTest.java:51)
```

**Comment by paulo-reichert** [comment]
Changes made:
- Moved the deployment manifest inline on the Jenkinsfile. 
- Tokenized the appName to use the GIT commit number to create a unique application.
- Added the deletion of the application to the Shutdown stage of the build
- Added a parameter to the integration tests so that they run against the uniquely named instance

This will allow multiple PR deployments to happen in parallel.
