### ISSUE TITLE
Allow simultaneous Jenkins builds

### ISSUE THREAD

**Issue by j-barber** [GalateaRaj/fuse-starter-java#143]
Because the H2 db is configured to be backed by a file, and that file is static across builds, multiple Jenkins builds at the same time can interfere with each other over contention to the db.

[Example](https://jenkins.fuse.galatea-associates.com/job/jenkins-pipeline/job/feature%252Fissue-135-remove-checkstyle/2/consoleFull):
![image](https://user-images.githubusercontent.com/23705265/36547122-185e1d1e-17bb-11e8-96c7-16e6231a0013.png)

**Comment by paulo-reichert** [comment]
#145 duplicates this.

**Comment by paulo-reichert** [comment]
Moving to an in-memory database. 

Before the change, running unit tests while an instance of the app is alive:
![image](https://user-images.githubusercontent.com/13468907/36558067-e6640d1a-17d7-11e8-8fec-0195e1e2ae2b.png)

After the change, running unit tests while an instance of the app is alive:
![image](https://user-images.githubusercontent.com/13468907/36558147-18b87440-17d8-11e8-97f1-c5b79dc9b529.png)
