### ISSUE TITLE
Failed Develop builds should raise some alerts

### ISSUE THREAD

**Issue by j-barber** [GalateaRaj/fuse-starter-java#146]
A build failed after a merge to Develop, and was only noticed because we were looking at Jenkins.

Notifications should be sent out to someone... all collaborators?

[Example](https://jenkins.fuse.galatea-associates.com/job/jenkins-pipeline/job/develop/14/)

**Comment by paulo-reichert** [comment]
I'd suggest we send emails to the person that committed the code and the code owners, as all collaborators could potentially be the whole of Galatea, but I'm open to suggestions.

**Comment by GalateaRaj** [comment]
Can we use slack for this?  Notify the slack channel (#fuse-java-builds) that the build has failed as well as the individual.

**Comment by paulo-reichert** [comment]
![image](https://user-images.githubusercontent.com/13468907/36731870-0be005ec-1b9a-11e8-9de9-4bc4a77f15b0.png)
