### ISSUE TITLE
Clean up manifest files

### ISSUE THREAD

**Issue by paulo-reichert** [GalateaRaj/fuse-starter-java#155]
Issue Description
--
After the changes for issue #137 both manifest-dev.yml and manifest-local.yml will remain unused. We need to decide what to do with those, whether they should remain in the codebase and if so, how do we actually use them (i.e. for manual pushes to PCF).

Design
--
Remove manifest-dev.yml, since the build process will be solely responsible for deploying to dev and higher environments.
Keep manifest-local.yml with a bit of clean-up and some in-file instructional comments, to be used for testing of local branches during development.

Documentation Changes
--
Added section about Cloud Foundry: https://docs.google.com/document/d/1EqvSfrKaQa6zBF8QRjWMZeOifMZsl-jwCxCmhC2Q8S8/edit#heading=h.xacw9frrjqed

Test Evidence
--
* `cf push -f manifest-local.yml` successfully creates and starts a Cloud Foundry app:
[155_cfpush](https://user-images.githubusercontent.com/50337114/58265434-ac689680-7d4d-11e9-9ed7-d4c5bc54774a.PNG)
[155_pushed_app](https://user-images.githubusercontent.com/50337114/58263438-fbacc800-7d49-11e9-8011-1dd1433b8dde.PNG)

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by GalateaRaj** [comment]
Based on our experience, you can remove manifest-dev.yml but you should leave in manifest-local.yml to make it easy for developers to push to cloud foundry for testing.

Update google doc to discuss when to use manifest-local.yml.

**Comment by j-barber** [comment]
PR merged. Documentation still needs updating.

**Comment by j-barber** [comment]
Documentation updated
