### ISSUE TITLE
Stop github integration w/ Jenkins instance on Mystique

### ISSUE THREAD

**Issue by j-barber** [GalateaRaj/fuse-starter-java#168]
Issue Description
--
[Description of the issue, with example/screenshot. Description of what the desired behavior should be. Should be complete before Review is approved]

Occasionally GitHub reports a build as failing, but then gets that report from Mystique:
![image](https://user-images.githubusercontent.com/23705265/36908839-7494326c-1e0a-11e8-9ce8-6e0b55e373fa.png)

We should sever the connection between GitHub and Mystique to stop this.

Design
--
[Description of the root cause for the issue and how to resolve it. Should be complete before Review is approved]

Test Evidence
--
[include relevant tests and output. Should be complete before Review is approved]

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by j-barber** [comment]
@GalateaRaj -- is there some configuration in GitHub to send messages to Mystique for new branches/pull requests?

**Comment by alex-power** [comment]
Link to Mystique Jenkins: [https://mystique:444/jenkins](https://mystique:444/jenkins)
Removed the Github source from the Jenkins repo. 
![image](https://user-images.githubusercontent.com/25554707/37416739-fd786ab6-2784-11e8-9bb5-45512255978b.png)

The Jenkins repo was left intact, and the name was changed for clarity.
![image](https://user-images.githubusercontent.com/25554707/37416897-624fa8d2-2785-11e8-96e0-b943ac3792f3.png)
