### ISSUE TITLE
Decide/Configure Quality Gates

### ISSUE THREAD

**Issue by j-barber** [GalateaRaj/fuse-starter-java#179]
Issue Description
--
[Description of the issue, with example/screenshot. Description of what the desired behavior should be. Should be complete before Review is approved]

The standard Sonar Way quality gate is pretty permissive.
https://sonarcloud.io/organizations/galatea/quality_gates/show/9
![image](https://user-images.githubusercontent.com/23705265/37225080-7e9ea0c8-23a3-11e8-9631-c1783e3822ee.png)

What other metrics do we want to include in our gate?

Design
--
[Description of the root cause for the issue and how to resolve it. Should be complete before Review is approved]

Test Evidence
--
[include relevant tests and output. Should be complete before Review is approved]
![image](https://user-images.githubusercontent.com/23705265/37347110-793e8af6-26a7-11e8-9288-baa3906194f4.png)

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

2 Major issues failed the develop build:
![image](https://user-images.githubusercontent.com/23705265/37347302-e214bda2-26a7-11e8-81de-c7801fab98a0.png)

![image](https://user-images.githubusercontent.com/23705265/37347280-d7a28b74-26a7-11e8-9809-9f746340ec77.png)

**Comment by GalateaRaj** [comment]
Skipped Unit tests = 0
No blocker, critical, or major issues
Add technical debt = 0 
New code smells = 0

**Comment by j-barber** [comment]
Updated:
![image](https://user-images.githubusercontent.com/23705265/37347110-793e8af6-26a7-11e8-9288-baa3906194f4.png)
