### ISSUE TITLE
Add rest exception handling

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#18]
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/ControllerAdvice.html

**Comment by gala-dan** [comment]
A blog explaining a little bit about @ControllerAdvice - https://lankydanblog.com/2017/09/12/global-exception-handling-with-controlleradvice/

**Comment by j-barber** [comment]
Closing as duplicate of #14
