### ISSUE TITLE
Create documentation on a Google Doc to cover thought process and design in Fuse

### ISSUE THREAD

**Issue by paulo-reichert** [GalateaRaj/fuse-starter-java#180]
Issue Description
--
Right now our README.md is very high level. Going forward, that file should become only a description of how to get started with Fuse (set up IDE and get the application to run). We need documentation on a Google Doc that covers the decisions around the code, e.g. why did we use the annotations we did in the domain objects.

The Google Doc should be pinned to the #tech-java channel in Slack.

Design
--
Suggested documentation sections (feel free to add/remove):
* Lambdas and when to use them
* Lombok
    * Function
    * What annotations should we use for mutable entities
    * What annotations should we use for immutable entities
    * What annotations should we use for other components and services
* Spring REST services
    * Tracing messages
    * Exception handling
* JMS Listeners
* Logging
    * File vs. stdout/stderr
    * Single line exception logging
* Custom exceptions: when and how
* Galatea coding standards
    * Based on Google Style for Java
    * Extra rules
* CI builds
    * Jenkins
        * Pipeline stages
    * SonarQube vs. Checkstyle
    * Jacoco

Test Evidence
--
[include relevant tests and output. Should be complete before Review is approved]

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by mbarber-gala** [comment]
I think we have to be invited to collaborate on the project. Trevor is GalateaTrevor

**Comment by mbarber-gala** [comment]
https://docs.google.com/document/d/1EqvSfrKaQa6zBF8QRjWMZeOifMZsl-jwCxCmhC2Q8S8/edit

**Comment by paulo-reichert** [comment]
There's quite a bit of documentation written already. Developers working in fuse should be encouraged to update and maintain that documentation.

**Comment by mikegajda** [comment]
Relevant doc is here: https://docs.google.com/document/d/1eNODztmE8VPgQ8sEs-QyGH5rjXgx_2esnp5cJK2YF7Q/edit. Adding st:already-done label for furlough planning purposes
