### ISSUE TITLE
Rationalize lombok annotations

### ISSUE THREAD

**Issue by paulo-reichert** [GalateaRaj/fuse-starter-java#182]
Issue Description
--
Would be good to rationalize the lombok annotations we are currently using: they should make it clearer to the reader what the annotations mean and why they are placed in the code. 

`@Data` (https://projectlombok.org/features/Data) is a shortcut for `@Getter`, `@Setter`, `@ToString` and `@EqualsAndHashCode` so whenever we use that combination (i.e. domain objects) we should replace with the single annotation.

For objects that should be immutable, we should use `@Value` (https://projectlombok.org/features/Value). 

Objects that are annotated with `@Builder` (https://projectlombok.org/features/Builder) will automatically have a package-level private no-args constructor and a package-level all-args constructor created so there shouldn't be the need to specify `@AllArgsConstructor` and `@NoArgsConstructor` with access modifier private.

Spring `@Service` and `@Component` objects shouldn't need to override `toString()`, `equals()` or `hashCode()` so they shouldn't need the `@ToString` and `@EqualsAndHashCode` annotations.

Design
--
`@Data` annotations used in place of `@Getter`, `@Setter`, `@ToString` and `@EqualsAndHashCode`. 
`@ToString` and `@EqualsAndHashCode` removed from `@Component` and `@Service` classes `SettlementService` and `SettlementJmsListener`.

Test Evidence
--
![image](https://user-images.githubusercontent.com/25554707/37602610-13e8174c-2b63-11e8-9e25-7d3cbdac537d.png)

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by alex-power** [comment]
From the `@Builder` documentation: "You may not put any other method (or constructor) generating lombok annotation on a builder class though; for example, you can not put `@EqualsAndHashCode` on the builder class." Yet, we do it in more than one class.. 
Also, When you remove both `@AllArgsConstructor` and `@NoArgsConstructor` from an `@Builder` class, the jackson json parser fails (it needs a default no args constructor, which `@Builder` does not provide). But, when you only remove `@AllArgsConstructor` (which `@Builder` should provide automatically), `@Builder` throws an error saying that the all args constructor is undefined. The best solution is to include both constructor annotations. The only alternative is to explicitly define the constructors within the class.

**Comment by paulo-reichert** [comment]
2 things there:
- When it says that you may not put any other method (or constructor) generating annotation on a builder class, it refers to the builder itself, not the class that is annotated with `@Builder`. Our use case is still valid.
- The issue with the constructors is an interesting one. That information explaining why we specify the two constructor annotations should go in the GDoc that @mbarber-gala and @GalateaTrevor started as that is helpful info.
