### ISSUE TITLE
Enforce immutability on TradeAgreement and SettlementMission

### ISSUE THREAD

**Issue by gala-lightfoot** [GalateaRaj/fuse-starter-java#183]
Issue Description
--
Add the Lombok [@**Value** ](https://projectlombok.org/features/Value)annotation to TradeAgreement and SettlementMission to enforce immutability.  

Once generated/received into the system, their state should never change.

Design
--
[Description of the root cause for the issue and how to resolve it. Should be complete before Review is approved]

Test Evidence
--
[include relevant tests and output. Should be complete before Review is approved]

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by GalateaRaj** [comment]
I can understand why an agreement might be immutable although I would argue that per Galatea training, even an agreement can be cancelled.

But a mission definitely has a life cycle. How would 
we settle a mission if it is immutable?  I know that fuse doesn't have a function to manage mission lifecycle at the moment but that's a key part of a mission's purpose.

**Comment by gala-dan** [comment]
Following functional principles, wouldn't we simply create a new mission with a new state?
