### ISSUE TITLE
Create HAL database

### ISSUE THREAD

**Issue by paulo-reichert** [GalateaRaj/fuse-starter-java#185]
Issue Description
--
Design a database model for storing HAL and MetWith commands and responses. 

This database has to be flexible enough to support any format questions and responses. Also should be fairly human readable.

Design
--
[Description of the root cause for the issue and how to resolve it. Should be complete before Review is approved]

Test Evidence
--
[include relevant tests and output. Should be complete before Review is approved]

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by GalateaEbbs** [comment]
Was this implemented or a decision made to close this out?
