### ISSUE TITLE
Review Pivotal Web Services tier

### ISSUE THREAD

**Issue by paulo-reichert** [GalateaRaj/fuse-starter-java#192]
Issue Description
--
We currently use [Pivotal Web Services](https://run.pivotal.io/) to deploy and run Fuse. As we plan to turn the new HAL implementation in Fuse into a production application running continuously we need to identify the best hosting environment.

Questions to be answered are primarily:
- Can we do websockets in PWS?
- What is the price?
- Databases

#### Websockets
PWS seems to support secure websockets connections (`wss:`) over port 4443. It does not seem to support non-secure connections (`ws:`). Some more info can be found [here](https://docs.run.pivotal.io/concepts/http-routing.html).

#### Pricing
Pricing for PWS is calculated on a GB-hr basis. That is the amount of RAM required by the app and how long the app is run for. 1GB-hr costs $0.03. 

For Java applications, Pivotal recommends each instance to have 1GB of RAM given the application service that is embedded in the image. If we run that application for the whole month, aprox. 730 hours, the cost will be $21.90/mo.

2 instances (for redundancy) with the same amount of memory will double that cost. Similarly, if we halve the amount of RAM we will half the cost.

#### Databases
There seem to be a few databases available in the Pivotal marketplace with free tiers. Need to check whether these databases can be used with PWS and whether they impact the memory requirements for the application.

#### Other options
There is an alternative that is to use Pivotal Cloud Foundry (instead of PWS) on AWS. The pricing structure for that is very opaque and we would incur licensing costs for PCF as well as resource costs for an Amazon private cloud. 

#### Concerns
As of 3/19 we have $49.32 trial credits remaining, which expire on 11/15. We need to move away from the trial tier before either the credit above or the expire date lapse.

Design
--
Pivotal recommends applications running in the JVM to be allocated 1GB of memory or more. I'd recommend the following design:

|Environment|Instances|Memory|Running time|Cost|Comments|
|---|---|---|---|---|---|
|Production|1|1GB|Continuous|$21.00/mo||
|QA|1|1GB|Continuous|$21.00/mo|can reduce this to a more ad-hoc schedule based on requirements|
|Development|Variable|512MB|CI|$0.03/hour|we spent $2.24 worth of credits from 2/15 to 3/15 running only CI builds with $0.01 on average per CI run|

Test Evidence
--
[include relevant tests and output. Should be complete before Review is approved]

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by GalateaRaj** [comment]
Let's go with 1 instance in prod for now.  No need for DR.  $21/month is totally fine.

I assume QA doesn't need to run continuously and that we can bring it up and down on an adhoc schedule.  That should help offset some of that cost.

Dev is fine.  As you point out, pretty cheap.

**Comment by paulo-reichert** [comment]
Agree on all accounts. Will our tier upgraded and payment info set up.

**Comment by paulo-reichert** [comment]
Our PWS subscription is set up and operational. Currently we do not have a prod instance deployed.
