### ISSUE TITLE
Create Fuse documentation - Lombok

### ISSUE THREAD

**Issue by mbarber-gala** [GalateaRaj/fuse-starter-java#201]
Issue Description
--
What annotations should be used for:
Functions
Mutable entities
Immutable entities
Other components and services

https://docs.google.com/document/d/1EqvSfrKaQa6zBF8QRjWMZeOifMZsl-jwCxCmhC2Q8S8/edit#

**Comment by Gala-Sortino** [comment]
Looking at the current documentation, these sections seem to have already been documented?

https://docs.google.com/document/d/1EqvSfrKaQa6zBF8QRjWMZeOifMZsl-jwCxCmhC2Q8S8/edit#heading=h.gy2hov5n7fcf

Is there anything in particular missing? Or is this issue resolved?

**Comment by GalateaFarhaad** [comment]
Sections for mutable entities and immutable entities were already present. I added a section for other components and services.

Review of the documentation is needed so that it can be finalized and this issue closed.
