### ISSUE TITLE
Demonstrate how to return different content types from a rest service

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#205]
Issue Description
--
Many of our REST applications need to support content negotiation between the client and the server.  Spring RestController offers annotations that aid with this (using content type and accepts headers).  It would be great if FUSE can provide an example of how the same REST endpoint can return json, xml, csv or xls based on the accepts header.

Design
--
* Override `configureContentNegotiation()` and `configureMessageConverters()` methods in MvcConfig (which extends `WebMvcConfigurerAdapter`) to configure how content negotiation will work and what converters will be used to convert incoming or outgoing HTTP data
* Create custom `HttpMessageConverter` implementations to perform the CSV and XLSX conversions
* Set `consumes` and `produces` values in the `@RequestMapping` annotations on the RestController endpoints to specify which MIME types are supported for that particular endpoint
* For any Java classes which are to be converted to/from XML, add a `@XmlRootElement(name = "myElementName")` annotation to the class
* For any Collections which are to be converted to/from XML, CSV, or XLSX, create a wrapper class holding the collection

Documentation Changes
--
Added Content Negotiation section https://docs.google.com/document/d/1EqvSfrKaQa6zBF8QRjWMZeOifMZsl-jwCxCmhC2Q8S8/edit#heading=h.q8lm6l3zbouu documenting the design above.

Test Evidence
--
* `SettlementRestControllerTest` and `SettlementProtoRestControllerTest` have tests that test the content configuration.
[Controller Tests](https://user-images.githubusercontent.com/50337114/57874922-a881c500-77df-11e9-9933-a0d341873bf5.PNG)
* When running locally, request bodies with different content types can be sent through Postman
[JSON request](https://user-images.githubusercontent.com/50337114/58358720-149ea180-7e4e-11e9-84dc-905e1a5f4e57.PNG)
[XML request](https://user-images.githubusercontent.com/50337114/58358723-15373800-7e4e-11e9-844b-296adab38be6.PNG)
[Proto request body](https://user-images.githubusercontent.com/50337114/58358721-15373800-7e4e-11e9-8e78-ac796a0d22ff.PNG)
[Proto request headers](https://user-images.githubusercontent.com/50337114/58358722-15373800-7e4e-11e9-94d9-7beaec397796.PNG)
* When running locally, requests through Postman get back the content type in the Accept header (or, alternately, the format param)
[JSON response](https://user-images.githubusercontent.com/50337114/57875050-f3034180-77df-11e9-8e52-58dcda26c78f.PNG)
[XML response](https://user-images.githubusercontent.com/50337114/57875052-f39bd800-77df-11e9-9225-55c7de473570.PNG)
[Proto response](https://user-images.githubusercontent.com/50337114/57875051-f3034180-77df-11e9-8c49-d3cbbc17e8c4.PNG)
[CSV response](https://user-images.githubusercontent.com/50337114/59286676-251c8d80-8c3e-11e9-878e-a1ec615b1ec5.PNG)
[XLSX response raw](https://user-images.githubusercontent.com/50337114/59286678-264dba80-8c3e-11e9-926b-3a372cec6a27.PNG)
[XLSX response in Excel](https://user-images.githubusercontent.com/50337114/59286677-25b52400-8c3e-11e9-984d-81d5b4b0e82e.PNG)

Validation in Develop
-- 
* Request bodies with different content types can be sent through Postman
[JSON request](https://user-images.githubusercontent.com/50337114/58359347-0ef68b00-7e51-11e9-9ee0-5ca05a1035a4.PNG)
[XML request](https://user-images.githubusercontent.com/50337114/58359350-0ef68b00-7e51-11e9-84d1-089799ea8044.PNG)
[Proto request body](https://user-images.githubusercontent.com/50337114/58359348-0ef68b00-7e51-11e9-8b95-ba3fa4d27dcb.PNG)
[Proto request headers](https://user-images.githubusercontent.com/50337114/58359349-0ef68b00-7e51-11e9-9e86-f2ffef47e4bc.PNG)
* Requests through Postman get back the content type in the Accept header (or, alternately, the format param)
[JSON response](https://user-images.githubusercontent.com/50337114/57881527-81cb8a80-77ef-11e9-882d-5fb138a647b2.PNG)
[XML response](https://user-images.githubusercontent.com/50337114/57881526-81cb8a80-77ef-11e9-802f-0bb901ac1aea.PNG)
[Proto response](https://user-images.githubusercontent.com/50337114/57881528-81cb8a80-77ef-11e9-8a57-530de9ce99df.PNG)
[CSV response](https://user-images.githubusercontent.com/50337114/59640820-404f3780-912d-11e9-8c10-9ccb693eb169.PNG)
[XLSX response raw](https://user-images.githubusercontent.com/50337114/59640824-40e7ce00-912d-11e9-8350-0d7c7971e654.PNG)
[XLSX response in Excel](https://user-images.githubusercontent.com/50337114/59640821-404f3780-912d-11e9-88f0-0e237c703b47.PNG)

**Comment by paulo-reichert** [comment]
Need to flesh out the description, update the documentation and close this issue.

**Comment by GalateaFarhaad** [comment]
Updated the description and the documentation.

Issue is ready to be reviewed for closure.

**Comment by j-barber** [comment]
Description includes supporting csv & xls, so we should add support for those as well.
