### ISSUE TITLE
Show how to define the port a Spring Boot application should run on

### ISSUE THREAD

**Issue by gala-dan** [GalateaRaj/fuse-starter-java#210]
Issue Description
--
By default, Spring Boot will run on port 8080. However, there may be scenarios where we need to run on an explicitly defined port. According to the [documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-change-the-http-port) we have 2 options for this:

1. Via application.yml
2. Via a command line parameter

Option 2 feels more 12-factor compliant. Would we need to update the <argLine> element in pom.xml to include the parameter for explicitness?

Design
--
- Modify run configuration files (Application.xml for IntelliJ and fuse-starter-java-app.launch for Eclipse) to include server.port as a program argument (--server.port=8080)
- To make the command argument required to ensure the app is not run on the wrong port by mistake, have Application implement ApplicationRunner and override the run method as done here: https://memorynotfound.com/spring-boot-passing-command-line-arguments-example/ and have the run method check if args.containsOption(“server.port”) and throw an exception if false

Documentation Changes
--
Add a sentence explaining where the port is set and how to change it.  One possible place to put this in the readme would be in the “run stuff” section of each editor, since this section already mentions some configuration information.

Test Evidence
--
![image](https://user-images.githubusercontent.com/20132996/45904692-c9625980-bdbb-11e8-9aba-386e47f58db8.png)

### Logs when --server.port set to 9090 in run configuration
![image](https://user-images.githubusercontent.com/20132996/45904927-8e145a80-bdbc-11e8-8ac2-471effcc5491.png)

### Logs when server port not set
![image](https://user-images.githubusercontent.com/20132996/45905007-d764aa00-bdbc-11e8-94e7-aa048ef0fdee.png)

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by gala-lightfoot** [comment]
Some info:
https://memorynotfound.com/spring-boot-passing-command-line-arguments-example/

Command-line will always override any config defined properties.

**Comment by paulo-reichert** [comment]
Should implement it via command line and it should be required to ensure that the wrong port is not used by mistake. The implementation should show that.
