### ISSUE TITLE
Consider incorporation of a data mapping library

### ISSUE THREAD

**Issue by GalaFirsh** [GalateaRaj/fuse-starter-java#217]
Issue Description
--
Many of our REST applications are required to transform data from the existing schema of their underlying data store into the desired domain model(s) to be exposed via REST API.  There are ~several~ many tools out there that aid with this which don't involve the standard manual solution:  "_Most programmers will develop some sort of custom mapping framework and spend countless hours and thousands of lines of code mapping to and from their different data objects_" (http://dozer.sourceforge.net/documentation/whymap.html)

It would be great if FUSE can provide an example of which tool to best use for this situation.
* One candidate is http://modelmapper.org/ which seems intuitive and powerful yet streamlined
* DOZER mentioned above also shows potential, but may be a bit too robust for this use-case
* Orika also seems neat http://orika-mapper.github.io/orika-docs/ which has better performance than Dozer (http://www.baeldung.com/orika-mapping) due to generating code instead of relying on reflection
* And more!  Such as:
* http://mapstruct.org - Create interfaces that auto-generate the mapping code, also works with Lombok
* https://github.com/jmapper-framework/jmapper-core - Can configure destination by annotation
* http://www.selma-java.org - Also interface based
* Other possible solutions?

This guy seems to have gone through a lot of the same debate and settled on either Selma or MapStruct, finally going with Selma:
* Part 1:  http://vytas.io/blog/java/Java-object-to-object-mapping-which-framework-to-choose/
* Part 2:  http://vytas.io/blog/java/Java-object-to-object-mapping-which-framework-to-choose-Part-2/

Selma and MapStruct also have much better performance compared to Orika, ModelMapper, and Dozer:
* https://github.com/arey/java-object-mapper-benchmark

Debate on MapStruct VS Selma by the authors themselves on StackOverflow:
* https://stackoverflow.com/questions/34786737/java-mapping-selma-vs-mapstruct

Libhunt comparison between many of the tools:
* https://java.libhunt.com/categories/337-bean-mapping

As a counterpoint to all of this, and why one should simply manually convert the objects:
* http://www.javatronic.fr/articles/2014/05/21/java_bean_mapping_is_wrong_lets_fix_it.html

Design
--
[Description of the root cause for the issue and how to resolve it. Should be complete before Review is approved]

Documentation Changes
--
[Description of changes necessary to the Fuse documentation due to the changes in response to this issue. Should be complete before Review is approved]

Test Evidence
--
[include relevant tests and output. Should be complete before Review is approved]

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by cbaltera** [comment]
See links above for information, no generally applicable best practice (very situational).

**Comment by cbaltera** [comment]
An additional link:
https://www.baeldung.com/java-performance-mapping-frameworks
