### ISSUE TITLE
Jenkins builds fail when commit message contains a single quote

### ISSUE THREAD

**Issue by paulo-reichert** [GalateaRaj/fuse-starter-java#222]
Issue Description
--
notifySlack() in the Jenkinsfile script will fail if the commit message for the last build contains a single quote.

Design
--
[Description of the root cause for the issue and how to resolve it. Should be complete before Review is approved]

Documentation Changes
--
[Description of changes necessary to the Fuse documentation due to the changes in response to this issue. Should be complete before Review is approved]

Test Evidence
--
[include relevant tests and output. Should be complete before Review is approved]

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by GalaHarley** [comment]
Seems to be fixed by Farhaad as part of #176

**Comment by GalateaEric** [comment]
agreed
