### ISSUE TITLE
Document decision matrix on how to interact with a database

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#230]
Issue Description
--
We have come up with a decision matrix as a part of #53 .  Let's document this in the FUSE google doc.

Design
--
N/A

Documentation Changes
--
See above.  This issue is about documentation changes.

Test Evidence
--
N/A

Validation in Develop
-- 
N/A

**Comment by mikegajda** [comment]
This appears to be complete: https://docs.google.com/document/d/1eNODztmE8VPgQ8sEs-QyGH5rjXgx_2esnp5cJK2YF7Q/edit#heading=h.ncp0tei2zg48 under "Interacting with a Database"
