### ISSUE TITLE
Possible improvement: Change getMessage to toString in RestExceptionHandler 

### ISSUE THREAD

**Issue by wmvsilva** [GalateaRaj/fuse-starter-java#235]
Issue Description
--
After using the code from `RestExceptionHandler`, we noticed a potential issue. In `RestExceptionHandler`, some methods create an `ApiError` like the following:
> ApiError error = new ApiError(HttpStatus.NOT_FOUND, exception.getMessage());

However, if the message of the exception is null, this can cause another exception to be thrown since the `message` field on `ApiError` is marked `@NonNull`. After modifying the code for other types of exceptions, we found that we were getting exceptions with a null message.

It may be useful to change the code to use `exception.toString()` which returns the exception and exception message and is never null. Alternatively, some null-check could be added as a precaution.

Design
--
[Description of the root cause for the issue and how to resolve it. Should be complete before Review is approved]

Documentation Changes
--
[Description of changes necessary to the Fuse documentation due to the changes in response to this issue. Should be complete before Review is approved]

Test Evidence
--
![image](https://user-images.githubusercontent.com/43134061/45749024-52ce2c00-bc02-11e8-84ce-a4cbae83d071.png)

Test throwing a generic exception, without any message, comparing the result before and after fix:
### Returned REST result:
![image](https://user-images.githubusercontent.com/43134061/45759086-05ac8300-bc1f-11e8-9b56-3eda069cce85.png)
### Console/Log:
![image](https://user-images.githubusercontent.com/43134061/45759104-1230db80-bc1f-11e8-9836-6c0fd0109832.png)

### Returned REST result:
![image](https://user-images.githubusercontent.com/43134061/45759154-2ffe4080-bc1f-11e8-807e-d0ddf77d141c.png)
### Console/Log:
![image](https://user-images.githubusercontent.com/43134061/45759171-38ef1200-bc1f-11e8-8484-9a98cf5710b6.png)

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by GalateaEric** [comment]
ready to be designed.  Developer to confirm we like the exception.toString() as the right alternative.  Once the developer is good with that, proceed onwards.
