### ISSUE TITLE
Jenkins build failing due to parameter error in Jenkinsfile.

### ISSUE THREAD

**Issue by Gala-Sortino** [GalateaRaj/fuse-starter-java#236]
Issue Description
--
Jenkins builds are failing due to the parameter "pluginTimeout" inside of the JenkinsFile being set as an integer when it expects a string. Also, have to modify the parameters of "memory" and "instances" to type string as well.

This issue is evident in the main develop branch too, however as the last build was many months ago, it has not failed. This suggests between the last run of develop builds and now, an update has been made to something that has caused this change. 

Design
--
The fix for this is to change the parameters "pluginTimeout", "memory" and "instances" inside of the JenkinsFile to be a string instead of an integer.

Documentation Changes
--
No known documentation changes are needed.

Test Evidence
--
![image](https://user-images.githubusercontent.com/43134061/45741559-d5012500-bbef-11e8-9d6a-a5b067152eaa.png)

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by GalateaEric** [comment]
go for it.
