### ISSUE TITLE
Protect against log forging

### ISSUE THREAD

**Issue by gala-dan** [GalateaRaj/fuse-starter-java#243]
Issue Description
--
Static scanning of client code revealed a log forging vulnerability in our code relating to logging parameters received from an external source. Looking in BaseRestController it seems FUSE is exposed to this too (as we log the requestId, which is a string).

This obviously isn't a critical issue, but it is good to be aware of these types of issues.

See https://www.baeldung.com/jvm-log-forging for details.

To add more colour, this issue only came up after we delomboked the code before running the scan.

Design
--
[Description of the root cause for the issue and how to resolve it. Should be complete before Review is approved]

Documentation Changes
--
[Description of changes necessary to the Fuse documentation due to the changes in response to this issue. Should be complete before Review is approved]

Test Evidence
--
Before:
![image](https://user-images.githubusercontent.com/43134061/46091533-f2fbf600-c1aa-11e8-96b7-44d5ba02202d.png)

After:
![image](https://user-images.githubusercontent.com/43134061/46091553-014a1200-c1ab-11e8-9334-8002aefaa21f.png)

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by GalateaTom** [comment]
A temporary fix will be provided by branch feature/issue-243-protect-against-log-forging-TomEd.  Long term solution is to wrap the logging format in %encode{...}{CRLF} in all the log4j yml files.  e.g.
````value: "%d{yyyy.MM.dd HH:mm:ss.SSS} [%t] %-5level %logger{1.} - %X{internal-request-id}%X{external-request-id}%msg%n%xThrowable{separator(|)}"````
will become
````value: "%d{yyyy.MM.dd HH:mm:ss.SSS} [%t] %-5level %logger{1.} - %encode{%X{internal-request-id}%X{external-request-id}%msg}{CRLF}%n%xThrowable{separator(|)}"````
This requires version 2.10.0 or higher of the following dependencies:
````
<dependency>
	<groupId>org.apache.logging.log4j</groupId>
	<artifactId>log4j-api</artifactId>
	<version>${log4j.version}</version>
</dependency>
<dependency>
	<groupId>org.apache.logging.log4j</groupId>
	<artifactId>log4j-core</artifactId>
	<version>${log4j.version}</version>
</dependency>
<dependency>
	<groupId>org.apache.logging.log4j</groupId>
	<artifactId>log4j-slf4j-impl</artifactId>
	<version>${log4j.version}</version>
</dependency>
````
Currently the latest version of spring-boot-starter-log4j2 doesn't pull in version 2.10.0 or higher of those dependencies and we do not want to overwrite Spring Boot's defaults.  Once we have switched to a version of spring-boot-starter-log4j2 that does contain new enough versions of those dependencies we should be able to make use of %encode{...}{CRLF} without any changes to the pom

**Comment by GalateaEric** [comment]
we are good with using UriUtils for now to encode new line characters in the requestId.
