### ISSUE TITLE
Define preference for reading/writing CSV files

### ISSUE THREAD

**Issue by GalateaKyle** [GalateaRaj/fuse-starter-java#263]
Issue Description
--
We often need to read/write CSV files in our line of work.  Can we pick a standard for how to do this?  Should we use a publically available API?  If so which one?

Design
--
[Description of the root cause for the issue and how to resolve it. Should be complete before Review is approved]

Documentation Changes
--
[Description of changes necessary to the Fuse documentation due to the changes in response to this issue. Should be complete before Review is approved]

Test Evidence
--
[include relevant tests and output. Should be complete before Review is approved]

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by GalateaEric** [comment]
Raj is tentatively recommending apache's csv library.  We should do a thorough lit review for what our recommendation is.  Does spring have anything?

**Comment by GalateaFarhaad** [comment]
An example of serializing a POJO to CSV using the [Jackson CSV library](https://github.com/FasterXML/jackson-dataformats-text/tree/master/csv) was added in #205. See [`CsvSerializer`](https://github.com/GalateaRaj/fuse-starter-java/blob/a42eca83256b1c2f60a333827f4149b8f793a083/src/main/java/org/galatea/starter/utils/http/converter/CsvSerializer.java) for usage, and the associated [`CsvSerializerTest`](https://github.com/GalateaRaj/fuse-starter-java/blob/a42eca83256b1c2f60a333827f4149b8f793a083/src/test/java/org/galatea/starter/utils/http/converter/CsvSerializerTest.java) for example output.

**Comment by mikegajda** [comment]
Adding label st:already-done as seems we decided to go with Jackson CSV. If that's not the case this should be reopened.

**Comment by GalateaFarhaad** [comment]
I wouldn't say that this is necessarily done - Jackson CSV is what I used in the specific use case of 205, but there might be some other way we want to create CSVs in other use cases.

**Comment by cbaltera** [comment]
My semi-considered preferences are Jackson for writing and apache for reading, although I could see that varying depending on what I wanted to do with the data I read in (if it should be a map or a specific POJO).

**Comment by mikegajda** [comment]
Will reopen to bring back to Fuse Steerco for input

**Comment by mikegajda** [comment]
@cbaltera updated OneBar with information about handling CSV and best practices. Closing this.
