### ISSUE TITLE
Demonstrate how to use Spring Cloud Contract WireMock

### ISSUE THREAD

**Issue by GalateaEbbs** [GalateaRaj/fuse-starter-java#276]
Issue Description
--
Demonstrate how to use Spring Cloud Contract WireMock for stubbing external REST calls.

https://cloud.spring.io/spring-cloud-static/spring-cloud-contract/1.1.2.RELEASE/#_spring_cloud_contract_wiremock

**Comment by cbaltera** [comment]
added dependency on spring-cloud-contract-wiremock in #311 to allow random port selection for tests

**Comment by mikegajda** [comment]
SteerCo: Unless you own both sides of the boundary for a service, Cloud Contract, won't be useful, therefore, we're recommending not to use this. (Except if you need the dependency to allow you to use random ports w/ Wiremock as in #311, in which case, spring-cloud-contract-wiremock gets the job done)
