### ISSUE TITLE
Add new or modify current Application run config to print logs with log4j-stdout.yml

### ISSUE THREAD

**Issue by GalateaEbbs** [GalateaRaj/fuse-starter-java#279]
Issue Description
--
Either add a new Application run config or modify the existing one so that logs are printed to the console with the log4j-stdout.yml file. Much easier to see what's going on than looking through log files.

**Comment by GalateaFarhaad** [comment]
Under the logging section in the readme, there's instructions on how to log to stdout:
> To log to console instead of logging to file, set -Dlog4j.configurationFile=log4j2-stdout.yml as a VM option

That being said, I agree that setting log-to-stdout as the default setting for local running makes things easier. It matches what the application does in dev too, since it logs to stdout on Cloud Foundry.

**Comment by GalateaRaj** [comment]
Let's do both stdout and log file when running locally.
Cloud Foundry should continue to do stdout only
