### ISSUE TITLE
Upgrade to spring boot 2.1.x

### ISSUE THREAD

**Issue by GalateaEric** [GalateaRaj/fuse-starter-java#288]
Issue Description
--

Spring boot 1.5.x is no longer being maintained.  We should upgrade to the latest 2.1.x release.

https://spring.io/blog/2019/08/06/it-is-time-goodbye-spring-boot-1-x
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide

Design
--
#### Trace
Spring Boot 2 has removed the following classes we use:
`WebRequestTraceFilter`
`InMemoryTraceRepository`
`TraceProperties`

Instead they have provided the `org.springframework.boot.actuate.trace.http` and `org.springframework.boot.actuate.web.trace.servlet` packages as replacements. The biggest difference is that instead of using a Map<String, Object>, it now uses an [HttpTrace](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/actuate/trace/http/HttpTrace.html) object which stores the following information:

- Request
- Response
- Principal
- Session
- Timestamp
- Time Taken

Since we are currently manually adding a lot of this data (all but principal and session), this may simplify things for us. However, if we want to add things like internal/external request id and request-success, we may need to extend this functionality.
- Note: `HttpTrace` and its inner classes do not override `toString` for whatever reason, so proper logic would need us to extend this anyway.

#### Spring Data Core
Small Spring Data changes, such as `CrudRepository` method renaming.
- `findOne` becomes `findById`
- `findAll` becomes `findAllById`
- `save` becomes `saveAll`

#### Spring Cloud Feign
According to https://stackoverflow.com/questions/52365074/feignclient-in-spring-boot-2, we will need to import Feign for Spring Boot 2.x as follows:

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-openfeign</artifactId>
    <version>2.0.1.RELEASE</version>
</dependency>
```

#### Swagger
The latest (2.9.2) version of Swagger breaks with Guava 18, which is being automatically pulled in by `org.apache.activemq:activemq-broker`. Solution is to exclude Guava from this and have Swagger pull in Guava 20

https://github.com/springfox/springfox/issues/2682

#### Jetty
Weird circular dependency when trying to start up Jetty. Solved by upgrading to Spring boot. 2.1.0 instead of 2.0.0

```
2019.08.13 14:23:09.049 [main] WARN  o.e.j.w.WebAppContext - Failed startup of context o.s.b.w.e.j.JettyEmbeddedWebAppContext@4adf3582{/,[file:///C:/Users/tharley/AppData/Local/Temp/jetty-docbase.8649990230446172921.8080/, jar:file:/C:/Users/tharley/.m2/repository/io/springfox/springfox-swagger-ui/2.9.2/springfox-swagger-ui-2.9.2.jar!/META-INF/resources],UNAVAILABLE}
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthEndpoint]: Factory method 'healthEndpoint' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration$$EnhancerBySpringCGLIB$$a85dc3dd]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource': Post-processing of FactoryBean's singleton object failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.jdbc.DataSourceInitializerInvoker': Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource': Post-processing of FactoryBean's singleton object failed; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'scopedTarget.dataSource': Requested bean is currently in creation: Is there an unresolvable circular reference?
```

#### Hibernate
Migrating to SB2 causes errors when executing SQL in Hibernate:

```
Caused by: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE HIBERNATE_SEQUENCE (NEXT_VAL BIGINT) TYPE[*]=MYISAM "; SQL statement:
create table hibernate_sequence (next_val bigint) type=MyISAM [42000-197]
```

Changing the dialect from `org.hibernate.dialect.MySQLDialect` to `org.hibernate.dialect.MySQL5Dialect` fixed this.

Documentation Changes
--
[Description of changes necessary to the Fuse documentation due to the changes in response to this issue. Should be complete before Review is approved]

Test Evidence
--
[include relevant tests and output. Should be complete before Review is approved]

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by GalaHarley** [comment]
One of the changes in Spring Boot 2 is they completely removed Actuator's `trace` and replaced it with `httptrace`.

https://docs.spring.io/spring-boot/docs/current/actuator-api/html/#http-trace
https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/actuate/trace/http/package-summary.html

`trace` is used pretty heavily in FUSE, and it appears this new endpoint is not exactly a suitable replacement for our use cases, which are more generic than tracing HTTP request info. I think a broader discussion is needed on how to proceed on this.

**Comment by GalaHarley** [comment]
https://github.com/spring-projects/spring-boot/issues/9980

Main issue at hand for the Trace changes

**Comment by GalateaEric** [comment]
The general view of the steerco is that we should 

- Dump our custom trace implementation and embrace whatever spring boot 2 has for http tracing.  - That being said, do something of a feature comparison between our custom trace implementation and what spring boot 2 has and see if there's any gap we want to think about covering (and create an issue to do so). 
- For JMS tracing see if there's anything available in spring boot 2 to parallel what we did with our custom trace implementation.  Or do we look to use something like spring cloud sleuth to get performance information on JMS consumers.

**Comment by GalaHarley** [comment]
Default SB2 Trace features:
- timestamp
- principal
- session
- request
  - method
  - uri
  - headers
  - remoteAddress
- response
  - status
  - headers
- timeTaken

FUSE trace implementation additional features
- request body
- response body
- internal-request-id
- external-request-id
- request-success

We also add a number of custom headers to the response itself (in `FuseWebRequestTraceFilter.addAuditHeaders()', such as internalQueryId, externalQueryId, requestReceivedTime, and requestElapsedTime.

**Comment by GalaHarley** [comment]
New trace logging with the HttpTrace looks like this:

![image](https://user-images.githubusercontent.com/51339284/63053144-160cc280-beaf-11e9-9cd0-10ada71feade.png)

**Comment by GalateaEric** [comment]
merged to develop
