### ISSUE TITLE
Point Jenkins' cloud foundry step at a manifest file rather than use in-line

### ISSUE THREAD

**Issue by GalateaEric** [GalateaRaj/fuse-starter-java#291]
Issue Description
--

The issue we're running into is that the health check against tcp:8080 is timing out with the default settings when we push to cloud foundry.  The cloud foundry github plugin doesn't expose these properties with the in-line manifest file.  

However, this does force us to now create a new step in Jenkins where we do some variable substitution on the manifest file so we can still get unique app-names per each CI build.

Design
--
[Description of the root cause for the issue and how to resolve it. Should be complete before Review is approved]

Documentation Changes
--
[Description of changes necessary to the Fuse documentation due to the changes in response to this issue. Should be complete before Review is approved]

Test Evidence
--
[include relevant tests and output. Should be complete before Review is approved]

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by GalateaRaj** [comment]
Before we start this, please double check that variable substitution hasn't already been done.

**Comment by mikegajda** [comment]
This appears to be closed by 4fa00844416ac67aeceb7faeec2e8addf848cf5d. Manifest variable substitution is already in develop

**Comment by mikegajda** [comment]
Marking with label st:already-done to remove from the st:ready backlog in preparation for furlough work on fuse. If this was incorrect, I will reopen.
