### ISSUE TITLE
Add support for protobuf

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#39]
Show an example of how we would use protobuf for jms

**Comment by paulo-reichert** [comment]
I'm not sure there is an elegant way to use protobuf with Spring `@JmsListener` and `JmsTemplate`. The options I see for this are:

- Write a `ProtobufMessageConverter` that extends `MessageConverter`, but this is awkward as Protobuf does not lend itself to dynamic discovery of the message type (`Parser<MessageType>` being the brains here).
- Use `JmsListener` to receive a `byte[]` message and pass it into some application code that knows what the type of that message is to use the correct `Message.parseFrom()` interface.
- Ditch `JmsListener` and do it all by hand like good old times.

**Comment by GalateaRaj** [comment]
@paulo-reichert :  should this issue still be open?

**Comment by paulo-reichert** [comment]
Closing this. We implemented the option of receiving the byte[] and passing it to application code that can decode the message.
