### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#4]
Log4j2 seems to be the way to go. It's already in our pom, but we should make sure we have the latest version.  

We need to add log config yaml file some of these key concepts:
Logs should be rolled based on time. Rolled logs should be gz.
Old Logs should be archived (old = previous jvm runs and previous days) and gz into a separate directory.
Logging should be async
Stdout and stderr should go to special sync logs
Create info, error, warning logs.  
Show how to create logs for special layer (e.g. the message logger)

**Comment by j-barber** [comment]
"Log4j2 seems to be the way to go." -- what were the relevant details in this decision?

**Comment by GalateaRaj** [comment]
We had a discussion about it in #tech-java and I believe Augusta had a proposal that seemed sensible.

The highlights from my pov:
1.  It has a built in asyc appender
2.  It offers more throughput than logback
