### ISSUE TITLE
Utilize mdc to log request context info

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#43]
Internally generated id at start of trace (generate in AutoClosedTrace ctor)
Request specific id at start of trace (via a Tracer.addTraceInfo call from the web request filter, the jms listener container, or some other entry point specific method)
Request specific id at start of handler method call (via an annotation on the handler method call)

**Comment by j-barber** [comment]
Additional requirements: 

1. Internally generated id should be included in log statements
2. Externally provided id from rest requests should be included in log statements (if provided)
3. Externally provided id from JMS requests should be included in log statements (if provided)

**Comment by j-barber** [comment]
Also,
4. Update README with:
a. where/how internally generated ids are generated and added to MDC
b. where/how externally generated ids are looked for
b. where/how ids are pulled from MDC into log files

**Comment by j-barber** [comment]
Ensure issue exists for returning the Ids in any response
