### ISSUE TITLE
Add .editorconfig with style standards

### ISSUE THREAD

**Issue by GalateaBerto** [GalateaRaj/fuse-starter-java#44]

**Comment by GalateaRaj** [comment]
Please see comment on pull request on whether this belongs in fuse-settings or here.

**Comment by EricLeighCollins** [comment]
I would like to offer that we don't use .editorconfig.  My reasoning:

1. editor config at the moment appears to support a pretty limited feature set: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties -- basically it deals with tabs vs spaces and new line characters.  Both of which are already handled by the eclipse formatter config, and i presume by whatever intellij's analog is.  

2. if we have both the eclipse (and intellij analog) settings and .editorconfig I imagine it's more confusing to understand which takes precedence and where to manage what settings than the value we get out of consolidating 4 or 5 settings across IDEs into a new file

3. Everyone has to install another plugin for all of their IDEs to manage a couple settings that are already managed by the IDE-specific config files.  If Editor Config were fully featured so as to obviate still having IDE-specifc config files I think it would be worth it.

I also get the impression reading some of the issues on their github account that new features don't happen very quickly, and that the user audience seems to be more people using text editors like Atom, vim, etc... which would have more need for something like this as they don't have all editing features that something like eclipse has.  

I assume Galatea's general guideline is to use an IDE like Eclipse or IntelliJ and we don't really encourage people to start developing using emacs or atom or sublime...

To that end I'd like to remove .editorconfig from fuse-starter-java and close this ticket.

**Comment by adelsam** [comment]
I'm fine killing this.
