### ISSUE TITLE
Update README -- November 2017

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#47]

**Comment by adelsam** [comment]
Looking into this.

**Comment by GalateaEric** [comment]
1.  "how to run project" section of readme for intellij
2.  incorporate feedback from recent end-users
3.  Add tiny section on functionality

**Comment by gala-dan** [comment]
Can be closed.

**Comment by paulo-reichert** [comment]
Closed following @gala-dan comment.
