### ISSUE TITLE
Illustrate best practices on how a java application should interact with a db

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#53]
Show include how to:
use sprocs
manage transactions across services
provide audit fields (eg last updated by)
properly use connection pools (see #87 )
cache frequently queried data
illustrate best practices around joins
use a tool like flyway (since it's integrated with spring) to manage the database schema (https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-execute-flyway-database-migrations-on-startup) 
currently configure your jdbc driver (e.g. set fetch size #73 )
test your db operations

**Comment by j-barber** [comment]
Also: 
Bulk writes
Auditing messages into a db in a performant/scalable manner

**Comment by ButlerAndy** [comment]
Be careful with Triggers for audit - if you have a lot of updates they will slow things down a lot. This is another reason to handle DML with procedures. You can bulk update and move to Audit while managing the log.

Couple of other things:

- Always update/delete in batches (configurable if possible so size can be changed easily).
- Lock down audit columns so they cannot be changed by an insert or update. This is where a trigger is useful in smaller tables so they overwrite anything that a user tries to put in.
- Be careful of parameter sniffing in SQL Server.
- Be VERY aware of SQL Injection. Learn about it and make sure your code prevents it. This applies to both Java code and Procedures

**Comment by gala-dan** [comment]
Bonus points for using Oracle data types (requiring java.sql.Struct) and nested tables (requiring java.sql.Array).

**Comment by j-barber** [comment]
From Sam's comment on issue #65: We want to promote the use of spring-data and JPA, but we also need to include recommendations for bulk operations that JPA struggles with.

**Comment by GalateaEric** [comment]
raj to add some comments about the latest encounters with some more recent technologies

**Comment by GalateaEric** [comment]
```decision tree:

	- greenfield vs existing project

		-> greenfield

			- large record sets to write or retrieve?  large is > 10k-ish

				-> yes

					- is something simple and generic like multi-threaded batched jdbc inserts fast enough?
						-> yes 
							- do that.  Would like to see a canonical example in fuse. (spliterator/raj-erator) (See Issue #233)
						-> no 
							- investigate database specific tooling

							- JPA for small record set use cases, bcp, etc... for large record set
							- does your database offer an "in-process" bcp-esque functionality?
							- capturing errors from cmdline bcp processes is error prone and frail

				-> no
					- pure JPA.  Example in fuse to use MySQL. (See Issue #231)

		-> existing project

			- follow suit where possible.  Generally avoid adding new libs/deps to anything existing.

			- can you mock out the database interaction in a reasonable manner?

				-> no
					- complain
				-> yes
					- do that, but are you sure?  We have a new Galatea Software idea!

```

**Comment by GalateaRaj** [comment]
We need to make a decision on the best way to maintain your db schema.  Do we like flyway (since it's integrated with spring) to manage the database schema (https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-execute-flyway-database-migrations-on-startup) ?

**Comment by GalateaRaj** [comment]
We have an issue for JPA.  Now steerco need to figure out what to do for the rest of the decision tree (i.e the large record set branch and how to test the "existing project" branch) and recommend best practices.

**Comment by ButlerAndy** [comment]
I would like a Galatea "Best Practice" to be that we always create a UI for managing "database-stored" configuration/tasks. Things such as:

1. Setting flags to switch feeds on and off
2. Viewing logging tables
3. Generic record count checks/sanity checks that are not sufficient in Geneos
4. Start/Stop/Rerun ETL

And many more.

Without this, you need to use DBA's or rely on support to run code for you. With a UI backed by stored procedures and locked down for Support to use, we make our life and theirs a lot easier.

**Comment by GalateaEric** [comment]
in reply to Andy's:

~~1. Setting flags to switch feeds on and off~~ this seems like an application specific use case of config.  We'll address in issue: #2 where a config best practice can/should be to use on/off switches for features.
~~2. Viewing logging tables~~  fuse would recommend that you generally don't log to database tables.  
12-factor recommends we log to stdout.  Are we talking about database procedure logging?
~~3. Generic record count checks/sanity checks that are not sufficient in Geneos~~ extra-geneos monitoring was intended to be captured by #6 
~~4. Start/Stop/Rerun ETL~~ this seems pretty application specific.  Yes, we would recommend that you have control over starting and stopping runs.

The broader take-away here is that we will look to create more functionality in fuse that demonstrates batch data load processing.  The existing fuse development is very REST and messaging focused so far.  It's absolutely a good idea to expound on how to build an ETL/datamart-like application which has to handle loading and re-loading many feeds and is database heavy.  Will link to the umbrella issue when it's created: #232

**Comment by GalateaRaj** [comment]
Finally!
