### ISSUE TITLE
EhCache configuration in JavaConfig is unnecessary w/ Spring Boot. Remove CachingConfig 

### ISSUE THREAD

**Issue by joshua-philpott** [GalateaRaj/fuse-starter-java#63]
@EnableCaching will automatically setup the EhCacheManagerFactoryBean and the CacheManager

**Comment by EricLeighCollins** [comment]
so, i removed the CachingConfig class and put the @EnableCaching annotation over on to the AppConfig class.  However, given there's no feedback from spring boot about whether caching is in fact enabled or not or what cache manager implementations it's using I'm unconvinced.  I think some more time to explore caching in general is probably in order.

**Comment by EricLeighCollins** [comment]
found #38 which i think would be useful.

**Comment by j-barber** [comment]
Adding some evidence to the discussion:

Removing CachingConfig.java but keeping ehcache.xml continues to use ehCache and caches correctly.
This is the same behavior as leaving CachingConfig and ehcache.xml in place.

See here for a comparison of the beans that are actually instantiated in these two configurations:
[withoutCachingConfigWithEhCacheXml.txt](https://github.com/GalateaRaj/fuse-starter-java/files/1724631/withoutCachingConfigWithEhCacheXml.txt)
[withCachingConfigAndEhCacheXml.txt](https://github.com/GalateaRaj/fuse-starter-java/files/1724622/withCachingConfigAndEhCacheXml.txt)

Evidence that caching is working (notice no SQL call on the 2nd invocation):
![cachingworking](https://user-images.githubusercontent.com/23705265/36213379-8fbe5e98-1174-11e8-8a3f-455eb85386b3.PNG)

Removing both CachingConfig.java and ehcache.xml caches correctly, but doesn't use ehCache.
[withoutCachingConfigOrEhCacheXml.txt](https://github.com/GalateaRaj/fuse-starter-java/files/1724636/withoutCachingConfigOrEhCacheXml.txt)

Bean definitions taken from here:
![beandefinitionsnapshot](https://user-images.githubusercontent.com/23705265/36213390-9790cbba-1174-11e8-8eb2-8eb49532ee14.PNG)

**Comment by j-barber** [comment]
This is a useful reference for Spring Caching: https://docs.spring.io/spring/docs/current/spring-framework-reference/integration.html#cache

And a reference for what Spring Boot adds:
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html#_supported_cache_providers

**Comment by j-barber** [comment]
Commit to remove CachingConfig checked in referencing issue #38... Whoops.

**Comment by paulo-reichert** [comment]
Removing the CacheConfig also renders the spring-context-support dependency redundant and that can be cleared out of the POM.
