### ISSUE TITLE
Update the Spring Boot dependency version

### ISSUE THREAD

**Issue by gala-dan** [GalateaRaj/fuse-starter-java#64]
Currently using 1.4.1 but 1.5.2 is available.

**Comment by EricLeighCollins** [comment]
upgraded to 1.5.3 as the most recent from spring: http://projects.spring.io/spring-boot/ 

looks like 2.0 is right around the corner!

**Comment by GalateaEric** [comment]
we're at 1.5.6 as of 12/1/2017.  Current is 1.5.9, which is close enough, 2.0 still not out yet.  Closing this ticket...
