### ISSUE TITLE
Gather consensus for Galatea's best practice on what criteria should fail Sonar analysis

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#69]
Define what is worthy of failing the build and fail the build based on that.

We expect this to serve as a guideline for failing the build at the client due to Sonar issues.

**Comment by EricLeighCollins** [comment]
https://github.com/SonarQubeCommunity/sonar-build-breaker/ should help in terms of the acutal mechanism of failing the build based on sonar qube results.

**Comment by gala-dan** [comment]
Can close this once Travis build is demised in favour of Jenkins.

**Comment by GalateaEric** [comment]
Renamed to be more appropriate now that we use Jenkins to initiate the sonar stuff rather than Travis.  I believe we are still rocking 100% defaults on sonar cloud.  I presume other people have opinions on what criteria to configure.

**Comment by j-barber** [comment]
Closing as duplicative of issue #176
