### ISSUE TITLE
Set up sonar

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#7]
This should run as a part of our travis CI build.  We should also be able to run sonar analysis from our IDE.

We should also consider failing the build if our tech debt increases beyond a threshold or if our RCI drops below a threshold.

**Comment by GalateaRaj** [comment]
Sweet.  This is done.  https://sonarqube.com/dashboard/index/org.galatea:fuse-starter-java

**Comment by j-barber** [comment]
That link didn't work for me, but this did:
https://sonarqube.com/dashboard?id=org.galatea%3Afuse-starter-java
