### ISSUE TITLE
Input Aware Fast Return Methods

### ISSUE THREAD

**Issue by stephenwebel** [GalateaRaj/fuse-starter-java#76]
I frequently write methods that take in a collection of ids and performs some costly action with the provided ids. For example, `Collection<Instrument> fetchInstrumentsForIds(Collection<String> ids);` takes a list of Instrument identifiers and does some out of process call. Inevitably, the method ends up looking like this:
```
Collection<Instrument> fetchInstrumentsForIds(Collection<String> ids){
  if (ids.isEmpty()){
    return Lists.newArrayList();
  }
  // do the actual fetching
}
```

I want an annotation to handle this size checking and empty collection returning. The annotation would be processed and updated the method to fast return when the "id list" is empty.

e.g.
```
@InputAware("ids")
Collection<Instrument> fetchInstrumentsForIds(Collection<String> ids){
  // the size check is auto generated
  // do the actual fetching
}
```

**Comment by paulo-reichert** [comment]
Not sure we should do this. Basic validation can be done using standard libraries and #106 covers that. Other validation can be argued whether it should be in generic libraries or application code.

**Comment by j-barber** [comment]
Also... why not do this? Is this no longer in fashion?

```
Collection<Instrument> fetchInstrumentsForIds(Collection<String> ids){
  Collection returnCollection = Lists.newArrayList(); // assuming this is the right collection type for the job
  for (String id : ids) {
  // do the actual fetching
  }
  return returnCollection;
}
```
