### ISSUE TITLE
Use jenkins pipeline to build fuse-starter-java

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#79]
1. Set up a multi-branch pipeline build using a jenkins file that is checked into git.  This is how jenkins pipelines work:  https://jenkins.io/doc/book/pipeline/ and here is the section specific to multi-branch pipelines:  https://jenkins.io/doc/book/pipeline/multibranch/ 
2. Figure out which jenkins we can use to run the build.  Can we use Gala jenkins or will that not work with GitHub webhooks?  If not, we can use AWS jenkins but let's make sure to secure it properly.
3. We should support:  branch builds, pr builds, and develop builds.  Pr builds should report their status back into github so the reviewer can see the pr build status.
4. Once this is set up, let's remove the travis.ci files and update docs

**Comment by gala-dan** [comment]
Pipeline file has been created and merged to develop. Branch builds are detected via the webhooks.

PR builds are not automatically triggered but will look at that through issue #84.

1. Done
2. Setup AWS instance of Jenkins
3. Will look at as part of #84
4. Will do separately
