### ISSUE TITLE
Update SonarQube link

### ISSUE THREAD

**Issue by gala-dan** [GalateaRaj/fuse-starter-java#82]
The read me currently provides the SonarQube link as https://sonarqube.com/dashboard?id=org.galatea%3Afuse-starter-java. This needs to be updated to https://sonarcloud.io/dashboard?id=org.galatea%3Afuse-starter-java.

**Comment by gala-dan** [comment]
Have updated the link. However, instructions to configure SonarLint also need to be updated. Can't currently get SonarLint to use SonarCloud.

**Comment by j-barber** [comment]
Pictorially, how to configure SonarLint to use SonarCloud:

1. R-click on project -> 'SonarLint' -> 'Bind to SonarQube project'
![updatebinding](https://user-images.githubusercontent.com/23705265/36267145-33619cb4-1241-11e8-9488-64e453a62c11.PNG)

2. Click 'connect to a SonarQube server...'
![selectserver](https://user-images.githubusercontent.com/23705265/36267185-4c288ad2-1241-11e8-9bf3-e7d463a17544.PNG)

3. Choose SonarCloud and generate a token. Pick the Organization with Name: Open Source, Key: default, Description: This organization gathers....
![serverselection](https://user-images.githubusercontent.com/23705265/36267297-8bb28a9a-1241-11e8-8c74-5f4802b8467d.PNG)

4. Bind the project by finding 'starter-java'
![bindproject](https://user-images.githubusercontent.com/23705265/36267334-9ce13cda-1241-11e8-9c38-812599fa986e.PNG)

All done.
