### ISSUE TITLE
Add an example of calling an upstream rest service

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#85]
Along with examples of how to test it.

**Comment by j-barber** [comment]
I propose we close this issue as a duplicate of #23

**Comment by paulo-reichert** [comment]
Do we want to show anything more than what is shown in `SettlementRestControllerIntegrationTest.java`?

Assuming we're using feign, is there any testable code to write?

**Comment by j-barber** [comment]
Also, #23 and #85 are duplicates of each other. We should consolidate to one.

And agree w/ Paulo's question, anything left to show?

**Comment by paulo-reichert** [comment]
Closing this as we don't know whether there's anything worth illustrating at this point.
