### ISSUE TITLE
Use hikaricp for connection pooling

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#87]
And make sure it integrates nicely with actuator

**Comment by cbaltera** [comment]
Check whether this is happening automatically.

**Comment by mikegajda** [comment]
Spring boot rolled out HikariCP with Spring Boot 2, so we got this for free when we upgraded: https://github.com/spring-projects/spring-boot/issues/6013

**Comment by mikegajda** [comment]
Metrics from hikaricp are not exposed by default, reopening. Metrics need to be turned on by enabling this property: `management.endpoints.web.exposure.include: info, health, metrics`. As part of this task, make sure we're not exposing anything we don't want to expose by turning this on.

**Comment by mikegajda** [comment]
Because this info is exposed via JMX, we're closing this again. There needs to be broader discussion on what to expose via JMX/REST of Actuator, which will happen on another ticket.

**Comment by cbaltera** [comment]
Hikari JMX bean:
![image](https://user-images.githubusercontent.com/7673236/75192937-44534080-5723-11ea-9d50-0d580ad6b344.png)

Actuator JMX beans:
Health 
![image](https://user-images.githubusercontent.com/7673236/75193051-79f82980-5723-11ea-8b92-cf96c890de64.png)
Metrics
![image](https://user-images.githubusercontent.com/7673236/75193125-9bf1ac00-5723-11ea-8caf-7a934125261c.png)
