### ISSUE TITLE
demonstrate sensible exception management

### ISSUE THREAD

**Issue by GalateaEric** [GalateaRaj/fuse-starter-java#92]
eric [10:18 AM] 
we don't really seem to do much with exceptions in here

[10:19] 
can we get that on the roadmap somewhere?

basu [10:20 AM] 
sure.  although doesn't spring boot handle most of that for us

eric [10:20 AM] 
most of it, but we should have at the least some good examples of creating strongly typed exceptions with reasonable error messages

basu [10:20 AM] 
ah.. yes

[10:20] 
agree

[10:21] 
and ones that generate appropriate http response codes

eric [10:21 AM] 
i guess i would propose/ask whether we favor having many strongly typed exceptions

basu [10:21 AM] 
i'm a big fan of @SneakyThrows now

eric [10:21 AM] 
yeah, you can annotate the exception class with the http response code

basu [10:21 AM] 
but we should file a github issue

eric [10:21 AM] 
oh dear, what is @SneakyThrows?

kelley [10:22 AM] 
It makes Java useable

basu [10:22 AM] 
https://projectlombok.org/features/SneakyThrows

eric [10:23 AM] 
what I did on my last code base was to make many strongly typed exceptions which were all RuntimeExceptions

[10:23] 
so you can throw them from anywhere and they go all the way up to spring without having to do throws on the whole method chain

[10:24] 
but, it still makes you catch checked exceptions coming from your libraries, etc...

[10:24] 
that encourages your code to not return other people's exceptions out of your REST API

[10:25] 
and you're encouraged to only return sensible http codes and messages

[10:25] 
there's nothing dumber than returning an 500 NullPointerException out of a REST API

basu [10:25 AM] 
sounds like a debate brewing

[10:26] 
i like it

[10:26] 
let's create a github issue and discuss when we work on it

**Comment by paulo-reichert** [comment]
Closing this as the work done in #14 seems to cover what was discussed above.
