### ISSUE TITLE
Create an example integration test against the CF development space

### ISSUE THREAD

**Issue by GalateaEric** [GalateaRaj/fuse-starter-java#97]
Need one example of an integration test that runs as part of the Jenkins pipeline and interacts with the deployed CF instance of our app in the 'development' space.

Let's use feign to build some http requests and exercise the REST endpoints.  We'll save the JMS queue for later...

**Comment by j-barber** [comment]
Can this be closed as 'completed'? The SettlementRestControllerIntegrationTest uses Feign to hit the rest service deployed on CF.

**Comment by GalateaEric** [comment]
i think i was leaving it open as it hadn't yet made it into develop, etc...  that's my best guess at any rate.

**Comment by j-barber** [comment]
SettlementRestControllerIntegrationTest is in develop, though: https://github.com/GalateaRaj/fuse-starter-java/blob/develop/src/test/java/org/galatea/starter/entrypoint/SettlementRestControllerIntegrationTest.java

**Comment by GalateaEric** [comment]
oh, right, i was thinking in my head (i mean, where else do you think) that it was tied up with the gradle conversion.  Yes, then I would think you can close this if you're happy with the integration test example.  Is it up to your exacting standards?
